server:
  port: 7003

eureka:
#  server:
#    enable-self-preservation: false #禁用自我保护机制(不推荐)
  instance:
    hostname: eureka7003.com #eureka实例的主机名
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上来获取服务的注册信息
    service-url:
      #单机版 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka